### ISSUE TITLE
 No Server currently available

### ISSUE THREAD

**Issue by yehezkielnaomi** [Lazarus/soulworker-server#2]
Dear Sir Austin,
I have run the code and have this result:

[SoulWorker]	Starting...
[SoulWorker]	Initializing database.
[Database]	Checking connection... Connected!
[Game Network]	Listening on [::]:10200.
[Login Network]	Listening on [::]:10000.
[Char Network]	Listening on [::]:10100.
[Login Network]	Client connected from 127.0.0.1:49637.

but on client side it say **No Server Currently Available**

can i have solution from you for this matter, thank you in advance. 

best regard
Yehezkiel

**Comment by lazarus** [comment]
Different client version, I used 1.7.33.16 as far as I remember

**Comment by yehezkielnaomi** [comment]
so different version has different packet? i have 1.7.33.4

**Comment by lazarus** [comment]
That's correct, but server availability should not be changing. Any packet logs?

**Comment by yehezkielnaomi** [comment]
i dont know how to see packet log, but when starting it only have Game Network, Login Network and Char Network, Game World not show when server starting

**Comment by yehezkielnaomi** [comment]
any solution for this Sir Austin?

**Comment by kaiitokidd** [comment]
Hey, is there any site where we can get other client versions?

**Comment by yehezkielnaomi** [comment]
@kaiitokidd : mine is from sourceforge

**Comment by kaiitokidd** [comment]
maybe you could me the link?

**Comment by kaiitokidd** [comment]
pass*

**Comment by yehezkielnaomi** [comment]
here you go : https://gameforge.com/en-GB/play/soulworker

**Comment by kaiitokidd** [comment]
but, that is the latest i guess?

**Comment by yehezkielnaomi** [comment]
Yes, i belive, cos if u find old one ... thats very imposible

**Comment by kaiitokidd** [comment]
that kinda sucks.. hmm..maybe austin could provide?

**Comment by yehezkielnaomi** [comment]
yup...i waiting for solution from him, maybe he can spare time to update his files

**Comment by kaiitokidd** [comment]
can you add me on discord maybe? so we dont spam here xD

#Kingston2520

**Comment by lazarus** [comment]
This uses the KR client. You need an OnStove verified account to download it yourself.
https://soulworker.game.onstove.com/

Try asking around to see if anyone can zip the KR client for you.
